name: luna_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  http: 0.13.5
  eva_icons_flutter: 3.1.0
  intl: ^0.17.0
  dotted_border: 2.0.0+3
  timeago: 3.3.0
  google_fonts: ^4.0.3
  percent_indicator: 4.2.2
  lottie: ^2.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - loginDoctor.png
    - logo.png